[package]
name = "cssc"
version = "0.1.0"
authors = ["Jonas Sjödin <jonas@fowlit.com>"]
edition = "2018"

[[bin]]
name = "cssc"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"